# Artificial Neural Network

### Importing the libraries

In [49]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [50]:
tf.__version__ #find tensorflow version

'2.10.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [51]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [52]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [53]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [55]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #choose the column
#where you want to onehot encode so you can turn them into vectors
X = np.array(ct.fit_transform(X))

In [57]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [59]:
#feature scaling for NN. 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #fit for the Train 
X_test = sc.transform(X_test) #just transform for Test

## Part 2 - Building the ANN

### Initializing the ANN

In [60]:
ann = tf.keras.models.Sequential() #create the NN itself

### Adding the input layer and the first hidden layer

In [61]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# units = how many neurons you want in your first hidden layer
# Experiment with different hyperparameters( called that way because they wont be trained during our process)
# No rules of thumb. We expirement with number of Neurons
# activation function rectifier activation function. That's relu!!
# We can add hidden layer of drop layer

### Adding the second hidden layer

In [62]:
#second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [63]:
#output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#choose the number of output neurons and the activation function
#sigmoid gives you the prediction plus the probability of binary output is one!!
#thats why we choose sigmoid activation function
#if the output is NOT binary we need to choose softmax as output

## Part 3 - Training the ANN

### Compiling the ANN

In [64]:
#compile with optimizer, loss function and metrics (evaluate your mode)
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#optimizer -> stohastic gradient descent. best stohastic gradient descent is adam
#loss function -> when doing binary always use binary_crossentropy
#loss function -> for non binary it must be categorical_crossentropy 
#metrics -> ARRAY

### Training the ANN on the Training set

In [65]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#fit(the x train, the y train, batch size, number of full iterations)
#batch learning is more effiecient for learning compare results into a batch. Usually 32

Epoch 1/100
 22/250 [=>............................] - ETA: 1s - loss: 0.7063 - accuracy: 0.5227

2022-10-09 11:49:31.322031: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


250/250 [==============================] - 1s 5ms/step - loss: 0.5714 - accuracy: 0.7395
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4637 - accuracy: 0.7963
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4399 - accuracy: 0.7970
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4317 - accuracy: 0.8014
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4275 - accuracy: 0.8046
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4242 - accuracy: 0.8055
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4211 - accuracy: 0.8086
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4173 - accuracy: 0.8083
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4131 - accuracy: 0.8121
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4078 - accuracy: 0.8145
E

250/250 [==============================] - 1s 5ms/step - loss: 0.3315 - accuracy: 0.8636
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3321 - accuracy: 0.8641
Epoch 83/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3315 - accuracy: 0.8648
Epoch 84/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3314 - accuracy: 0.8624
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3316 - accuracy: 0.8650
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3312 - accuracy: 0.8624
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3311 - accuracy: 0.8658
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3315 - accuracy: 0.8640
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3313 - accuracy: 0.8638
Epoch 90/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3307 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [69]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#predict always needs double set of brackets. 2D ARRAY excpected from predict
#needs feature scaling!! our data is scaled
#on our test set and the prediction we only need transform and not fit!
# The fit(data) method is used to compute the mean and std dev for a given feature to be used further for scaling.
# The transform(data) method is used to perform scaling using mean and std dev calculated using the .fit() method.
# The fit_transform() method does both fits and transform.
#we need > 0.5 because we get the probability as a results.

1/1 [==============================] - 0s 16ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [97]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.68) #works for each row was 0.5 cha
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1571   24]
 [ 244  161]]


0.866